// ============================================================================
// about.js — renders the About tab's 4 region-character cards from
// window.DESTINATION.editorial.about (js/corfu-about.js / js/testdest-about.js,
// generated by scripts/extract-about.js / hand-written placeholder
// respectively).
//
// Hybrid Phase 2 migration: only these repeated, structurally-identical
// cards move to data. The hero banner, quick-facts pills, geography intro,
// and driving/weather teaser blocks around them stay static editorial HTML
// in index.html — they're prose, not a record type, so forcing them into
// JSON would add abstraction without adding value (see _audit/ for the
// full reasoning).
// ============================================================================

// Renders the region-card grid. No-op (leaves the grid empty) rather than
// throwing when a destination has no About data yet (null/missing — e.g.
// the content-free 'empty' destination).
function renderAboutRegions() {
    const grid = document.getElementById('about-regions-grid');
    if (!grid) return;

    const dest = window.DESTINATION;
    const regions = (dest && dest.editorial && dest.editorial.about && Array.isArray(dest.editorial.about.regions))
        ? dest.editorial.about.regions : [];

    grid.innerHTML = regions.map(r => {
        const label = escapeHtml(r.label || '');
        const emoji = escapeHtml(r.emoji || '');
        const title = escapeHtml(r.title || '');
        const description = escapeHtml(r.description || '');
        return `<div class="bg-white rounded-2xl shadow-sm hover:shadow-xl transition duration-300 p-6 border gt-border-hair hover-card premium-card">
            <span class="inline-block gt-bg-sunken gt-text-700 text-xs font-bold px-2.5 py-1 rounded-full mb-3">${label}</span>
            <h4 class="text-lg font-bold gt-text-900 mb-2">${emoji} ${title}</h4>
            <p class="text-sm gt-text-500 leading-relaxed">${description}</p>
        </div>`;
    }).join('');
}
window.renderAboutRegions = renderAboutRegions;

// Renders the "quick facts" pill row from
// window.DESTINATION.editorial.about.quickFacts (js/corfu-about.js /
// js/testdest-about.js, generated by scripts/extract-about-quickfacts.js /
// hand-written placeholder respectively). No-op (leaves the row empty)
// rather than throwing when a destination has no quick-facts data yet
// (null/missing — e.g. the content-free 'empty' destination), same
// convention as renderAboutRegions() above.
//
// Each pill is either {icon, text} (plain emoji/text, HTML-escaped) or
// {iconHtml, text} (raw markup, e.g. an inline <svg> icon — NOT escaped,
// same icon/iconHtml split as other raw-markup fields in this codebase).
function renderAboutQuickFacts() {
    const row = document.getElementById('about-quick-facts-pills');
    if (!row) return;

    const dest = window.DESTINATION;
    const facts = (dest && dest.editorial && dest.editorial.about && Array.isArray(dest.editorial.about.quickFacts))
        ? dest.editorial.about.quickFacts : [];

    row.innerHTML = facts.map(f => {
        const iconMarkup = f.iconHtml ? f.iconHtml : escapeHtml(f.icon || '');
        const text = escapeHtml(f.text || '');
        return `<span class="inline-flex items-center gap-1.5 gt-bg-accent-soft gt-text-accent text-sm font-semibold px-3.5 py-2 rounded-full">${iconMarkup} ${text}</span>`;
    }).join('');
}
window.renderAboutQuickFacts = renderAboutQuickFacts;
