// Auto-generated by scripts/extract-about.js (regions),
// scripts/extract-about-quickfacts.js (quickFacts), and
// scripts/extract-about-hero.js (heroBanner) from the original index.html.
// Do not hand-edit lightly — regenerate via those scripts if the source
// markup changes. Note: regions/quickFacts can no longer be re-extracted
// from a live index.html (that markup was replaced by empty containers in
// earlier migration rounds) - each newer extraction script carries the
// prior fields forward unchanged when regenerating this file.
window.CORFU_ABOUT = {
  regions: [
    {
      "id": "north",
      "label": "צפון",
      "emoji": "🏔️",
      "title": "צוקי חימר ותעלות טורקיז",
      "description": "הנוף הכי דרמטי באי: צוקי חימר לבנים (כף דראסטיס), מים בגוון טורקיז עז ותצורות סלע כמו תעלת האהבה. פחות מתאים למשפחות עם פעוטות בגלל הגישה התלולה, אידיאלי לצלמים."
    },
    {
      "id": "east",
      "label": "מזרח",
      "emoji": "🏖️",
      "title": "חופי חלוקים ומים רגועים",
      "description": "מוגן מרוחות ולכן הים כאן חם ורגוע במיוחד - האזור האהוב על משפחות. כפרים ציוריים כמו קלאמי וברבטי, קרוב מאוד לקורפו טאון ולנמל התעופה."
    },
    {
      "id": "west",
      "label": "מערב",
      "emoji": "🌅",
      "title": "שקיעות אגדיות, ים קריר",
      "description": "חשוף לגלי הים היוני הפתוח - המים קרירים וגליים יותר, אך הנוף פראי ובלתי נשכח. כאן נמצאות חלק מהשקיעות המצולמות ביותר ביוון, בפלאוקסטריצה ובלוגאס."
    },
    {
      "id": "south",
      "label": "דרום",
      "emoji": "🏜️",
      "title": "דיונות חול וחופים אינסופיים",
      "description": "שטוח, פחות תיירותי ומפתיע: דיונות חול ליד אגם קוריסיון, חופים ארוכים ורחבים ואווירה צעירה יותר. אידיאלי לספורט ימי כמו קייט-סרפינג."
    }
  ],
  heroBanner: {
    "imageAlt": "איור: אדריכלות ונציאנית בקורפו",
    "title": "היכרות עם קורפו: האי הירוק של יוון 🌿",
    "subtitle": "שכבה עבה של עבר ונציאני, בריטי וצרפתי הפכה את קורפו לאי הכי \"אירופאי\" ביוון - סמטאות אבן, מגרשי קריקט וקתדרלות לצד 217 ק\"מ של קווי חוף עוצרי נשימה. לפני שצוללים למסלול המפורט, הנה כל מה שכדאי לדעת כדי לתכנן טיול חכם."
  },
  quickFacts: [
    {
      "icon": "🏛️",
      "text": "כ-400 שנה תחת שלטון ונציאני"
    },
    {
      "icon": "🌊",
      "text": "217 ק\"מ קו חוף"
    },
    {
      "icon": "✈️",
      "text": "כשעתיים וחצי טיסה מת\"א"
    },
    {
      "icon": "🗣️",
      "text": "יוונית (אנגלית נפוצה מאוד בתיירות)"
    },
    {
      "iconHtml": "<svg class=\"icon-line\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M15.5 6.8a6.3 6.3 0 1 0 0 10.4\"></path><path d=\"M5.5 10.2h8M5.5 13.4h7\"></path></svg>",
      "text": "מטבע: יורו (€)"
    },
    {
      "icon": "🌡️",
      "text": "ספטמבר: 26-28°C, ים חמים"
    }
  ]
};
