// Auto-generated by scripts/extract-weather.js from the original index.html.
// Do not hand-edit lightly — regenerate via the script if the source markup
// changes. Each entry's fields are plain text (verbatim from the source
// table cells). "highlight" marks the recommended-months styling (May-Sep
// in the original markup, i.e. rows that carried gt-bg-accent-soft on the
// <tr>).
window.CORFU_WEATHER = [
  {
    "month": "ינואר - פברואר",
    "dayTemp": "14°",
    "seaTemp": "15°",
    "rainDays": "12-14",
    "description": "חורפי, קר וגשום מאוד. האי בתרדמת חורף ורוב בתי העסק לתיירים סגורים.",
    "highlight": false
  },
  {
    "month": "מרץ",
    "dayTemp": "16°",
    "seaTemp": "15°",
    "rainDays": "9",
    "description": "ניצני אביב, האי פורח וירוק בצורה מרהיבה, אך עדיין לא מתאים לרחצה בים.",
    "highlight": false
  },
  {
    "month": "אפריל",
    "dayTemp": "19°",
    "seaTemp": "16°",
    "rainDays": "7",
    "description": "מזג אוויר אידיאלי לטיולי טבע ורגליים. חג הפסחא נחגג בחודש זה והעיר מלאה.",
    "highlight": false
  },
  {
    "month": "מאי",
    "dayTemp": "24°",
    "seaTemp": "19°",
    "rainDays": "4",
    "description": "פתיחת העונה הרשמית! חמים ונעים במהלך היום, ערבים קרירים. הים עדיין קריר יחסית.",
    "highlight": true
  },
  {
    "month": "יוני",
    "dayTemp": "28°",
    "seaTemp": "23°",
    "rainDays": "2",
    "description": "אחד החודשים המומלצים! חם מספיק לבטן-גב, המים נעימים, ואין עומס תיירים מוגזם.",
    "highlight": true
  },
  {
    "month": "יולי - אוגוסט",
    "dayTemp": "32°+",
    "seaTemp": "26°",
    "rainDays": "0-1",
    "description": "שיא הקיץ. חם מאוד, לח ועמוס במיליוני מבקרים. המים בטמפרטורה נעימה ומזמינה.",
    "highlight": true
  },
  {
    "month": "ספטמבר",
    "dayTemp": "28°",
    "seaTemp": "25°",
    "rainDays": "5",
    "description": "החודש המנצח של קורפו. הים אגר חום כל הקיץ, עומס המבקרים יורד ומזג האוויר נעים.",
    "highlight": true
  },
  {
    "month": "אוקטובר",
    "dayTemp": "23°",
    "seaTemp": "22°",
    "rainDays": "9",
    "description": "סוף העונה. ימים חמים לסירוגין עם סופות וגשמים פתאומיים. מחירים אטרקטיביים.",
    "highlight": false
  },
  {
    "month": "נובמבר - דצמבר",
    "dayTemp": "16°",
    "seaTemp": "18°",
    "rainDays": "15",
    "description": "חזרה לעונת החורף. רטוב, קר ושקט מאוד ברחבי האי.",
    "highlight": false
  }
];
