// ============================================================================
// language.js — renders the Language & Daily Life tab's structured record
// types from window.DESTINATION.editorial.language (js/corfu-language.js /
// js/testdest-language.js, generated by scripts/extract-language.js / hand-
// written placeholder respectively).
//
// Hybrid Phase 2 migration: only the repeated, structurally-identical record
// types move to data — the 2 shopping streets, 4 souvenirs, 4 supermarket
// chains, and the 5 uniform phrasebook category cards (each a list of
// {hebrew, greek, transliteration} phrase triples). The no-malls intro
// paragraph, the pharmacies block, and the public-restrooms block inside
// #lang-shopping stay static editorial HTML in index.html — they're prose,
// not a record type.
//
// The phrasebook's 6th card ("💡 טיפ הגייה") is genuinely different from the
// other 5 — a single prose paragraph, not a phrase list — so it is NOT
// forced into the `phrases` shape. It travels as its own
// editorial.language.pronunciationTip field ({icon, title, html}) and
// renderPhrasebook() appends it after the 5 structured cards as a
// differently-shaped 6th card, matching the original markup.
//
// Every renderer here no-ops (leaves its container empty) rather than
// throwing when a destination has no language data yet (null/missing — e.g.
// the content-free 'empty' destination) — same convention as
// js/about.js's renderAboutRegions() and js/health-safety.js's renderers.
// None of these functions branch on DESTINATION.id — they are 100% generic.
// ============================================================================

function getLanguageData() {
    const dest = window.DESTINATION;
    return (dest && dest.editorial && dest.editorial.language) || null;
}

// One shopping-street row in #lang-shopping-streets.
function shoppingStreetHtml(s) {
    const mapsLinkHtml = s.mapsUrl
        ? `<a href="${escapeAttr(s.mapsUrl)}" class="gt-text-accent text-sm font-semibold hover:underline">📍 הצג במפה</a>`
        : '';
    return `<div class="flex gap-4 items-start gt-bg-sunken p-4 rounded-xl gt-hover-sunken transition-colors">
                    <div class="text-3xl mt-1">${escapeHtml(s.icon || '')}</div>
                    <div>
                        <h5 class="font-bold text-lg gt-text-900">${escapeHtml(s.name || '')}</h5>
                        <p class="gt-text-500 text-sm mb-2">${escapeHtml(s.description || '')}</p>
                        ${mapsLinkHtml}
                    </div>
                </div>`;
}

// Renders the shopping-streets list into #lang-shopping-streets.
function renderShoppingStreets() {
    const container = document.getElementById('lang-shopping-streets');
    if (!container) return;

    const lang = getLanguageData();
    const streets = (lang && Array.isArray(lang.shoppingStreets)) ? lang.shoppingStreets : [];
    container.innerHTML = streets.map(shoppingStreetHtml).join('\n                ');
}

// One souvenir list item in #lang-souvenirs-list.
function souvenirHtml(s) {
    return `<li class="flex items-center gap-4 p-4 gt-bg-accent-soft rounded-xl border gt-border-accent">
                        <span class="text-4xl drop-shadow-sm">${escapeHtml(s.icon || '')}</span>
                        <div>
                            <strong class="gt-text-accent block text-lg">${escapeHtml(s.title || '')}</strong>
                            <span class="text-sm gt-text-accent">${escapeHtml(s.description || '')}</span>
                        </div>
                    </li>`;
}

// Renders the souvenirs list into #lang-souvenirs-list.
function renderSouvenirs() {
    const container = document.getElementById('lang-souvenirs-list');
    if (!container) return;

    const lang = getLanguageData();
    const souvenirs = (lang && Array.isArray(lang.souvenirs)) ? lang.souvenirs : [];
    container.innerHTML = souvenirs.map(souvenirHtml).join('\n                    ');
}

// One supermarket-chain tile in #lang-supermarkets-grid.
function supermarketHtml(s) {
    return `<div class="bg-white p-3 rounded-lg shadow-sm border gt-border-hair">
                        <strong class="gt-text-accent block mb-1">${escapeHtml(s.name || '')}</strong>
                        ${escapeHtml(s.description || '')}
                    </div>`;
}

// Renders the supermarket-chain grid into #lang-supermarkets-grid.
function renderSupermarkets() {
    const container = document.getElementById('lang-supermarkets-grid');
    if (!container) return;

    const lang = getLanguageData();
    const supermarkets = (lang && Array.isArray(lang.supermarkets)) ? lang.supermarkets : [];
    container.innerHTML = supermarkets.map(supermarketHtml).join('\n                        ');
}

// One phrase line inside a phrasebook category card.
function phraseLineHtml(p) {
    return `<li><strong>${escapeHtml(p.hebrew || '')}:</strong> ${escapeHtml(p.greek || '')} <span class="gt-text-accent">(${escapeHtml(p.transliteration || '')})</span></li>`;
}

// One structured phrasebook category card (uniform phrase list).
function phrasebookCategoryHtml(c) {
    const phrases = Array.isArray(c.phrases) ? c.phrases : [];
    return `<div class="gt-bg-accent-soft rounded-xl p-5 border gt-border-accent">
                <h4 class="font-bold gt-text-accent mb-3 text-lg flex items-center gap-2">${escapeHtml(c.icon || '')} ${escapeHtml(c.title || '')}</h4>
                <ul class="text-sm gt-text-accent space-y-2">
                    ${phrases.map(phraseLineHtml).join('\n                    ')}
                </ul>
            </div>`;
}

// The 6th, prose-only pronunciation-tip card — same outer card shell as the
// 5 structured cards, but a single paragraph instead of a phrase list.
function pronunciationTipHtml(tip) {
    return `<div class="gt-bg-accent-soft rounded-xl p-5 border gt-border-accent">
                <h4 class="font-bold gt-text-accent mb-3 text-lg flex items-center gap-2">${escapeHtml(tip.icon || '')} ${escapeHtml(tip.title || '')}</h4>
                <p class="text-sm gt-text-accent leading-relaxed">
                    ${tip.html || ''}
                </p>
            </div>`;
}

// Renders the 5 structured phrasebook cards + the 6th pronunciation-tip
// card into #lang-phrasebook-grid.
function renderPhrasebook() {
    const container = document.getElementById('lang-phrasebook-grid');
    if (!container) return;

    const lang = getLanguageData();
    if (!lang) { container.innerHTML = ''; return; }

    const categories = Array.isArray(lang.phrasebook) ? lang.phrasebook : [];
    const cardsHtml = categories.map(phrasebookCategoryHtml).join('\n            ');
    const tipHtml = lang.pronunciationTip ? pronunciationTipHtml(lang.pronunciationTip) : '';

    container.innerHTML = cardsHtml + (tipHtml ? '\n            ' + tipHtml : '');
}

window.renderShoppingStreets = renderShoppingStreets;
window.renderSouvenirs = renderSouvenirs;
window.renderSupermarkets = renderSupermarkets;
window.renderPhrasebook = renderPhrasebook;
