        // Step 2.2: bakes the site's Mediterranean palette + radius/shadow
        // scale directly into Tailwind's own theme, so e.g. `.text-teal-600`
        // is GENERATED by the CDN's compiler already carrying the brand
        // color - no separate override rule fighting it for specificity
        // afterward. This is what let most of the old `!important` block
        // in <style> be deleted outright (not just de-flagged): once the
        // Tailwind-generated utility already produces the right value,
        // there is nothing left to override.
        //
        // A handful of rules remain in <style> on purpose: Tailwind's
        // hover:/focus: variants always resolve to the SAME theme value as
        // their base state for a given shade number, so a few spots that
        // need hover to shift to a genuinely different color than their
        // resting state (e.g. bg-teal-600 at rest, but a darker ion-900 on
        // hover) can't be expressed by the static palette below - those
        // stay as small, explicitly-commented exceptions.
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        teal:    { 50:'#eef4f8', 100:'#eef4f8', 200:'#237fae', 500:'#237fae', 600:'#14507a', 700:'#14507a', 800:'#14507a', 900:'#14507a' },
                        blue:    { 50:'#eef4f8', 100:'#e1edf5', 500:'#1a6494', 600:'#14507a', 700:'#14507a', 800:'#14507a', 900:'#14507a' },
                        indigo:  { 50:'#eef4f8', 100:'#eef4f8', 200:'#237fae', 500:'#237fae', 600:'#14507a', 700:'#14507a', 800:'#14507a', 900:'#14507a' },
                        cyan:    { 50:'#eef4f8', 200:'#237fae', 600:'#14507a', 700:'#14507a', 800:'#14507a' },
                        purple:  { 50:'#eef4f8', 100:'#e1edf5', 200:'#237fae', 600:'#14507a', 700:'#14507a', 800:'#14507a', 900:'#14507a' },
                        pink:    { 50:'#eef4f8', 800:'#14507a' },
                        green:   { 50:'#f2f5ea', 100:'#e6ecd8', 200:'#6d7a4f', 500:'#6d7a4f', 600:'#6d7a4f', 700:'#6d7a4f', 800:'#6d7a4f', 900:'#6d7a4f' },
                        emerald: { 50:'#f2f5ea', 200:'#6d7a4f', 400:'#6d7a4f', 600:'#6d7a4f', 700:'#6d7a4f', 800:'#6d7a4f', 900:'#6d7a4f' },
                        lime:    { 50:'#f2f5ea' },
                        amber:   { 50:'#f7ecd9', 100:'#f7ecd9', 200:'#b8934a', 300:'#b8934a', 400:'#b8934a', 600:'#b8934a', 700:'#8f6e2e', 800:'#8f6e2e', 900:'#8f6e2e' },
                        orange:  { 50:'#f7ecd9', 100:'#f7ecd9', 200:'#b8934a', 600:'#b8934a', 700:'#8f6e2e', 800:'#8f6e2e', 900:'#8f6e2e' },
                        yellow:  { 50:'#f7ecd9', 700:'#8f6e2e', 800:'#8f6e2e' },
                        slate:   { 50:'#faf9f6', 100:'#f2ecdf', 200:'#e7ddc7', 400:'#756e63', 500:'#6b6154', 600:'#6b6154', 700:'#423a30', 800:'#241f1a', 900:'#241f1a' },
                        gray:    { 50:'#faf9f6', 100:'#f2ecdf', 200:'#e7ddc7', 400:'#756e63', 500:'#6b6154', 600:'#6b6154', 700:'#423a30', 800:'#241f1a', 900:'#241f1a' },
                    },
                    borderRadius: { xl: '14px', '2xl': '16px', '3xl': '18px' },
                    boxShadow: {
                        sm: '0 1px 2px rgba(36,31,26,.06), 0 1px 3px rgba(36,31,26,.08)',
                        md: '0 3px 10px rgba(13,59,77,.08), 0 1px 4px rgba(36,31,26,.08)',
                        lg: '0 3px 10px rgba(13,59,77,.08), 0 1px 4px rgba(36,31,26,.08)',
                        xl: '0 10px 22px rgba(13,59,77,.10), 0 2px 8px rgba(36,31,26,.06)',
                        '2xl': '0 16px 34px rgba(13,59,77,.12), 0 4px 12px rgba(36,31,26,.07)',
                    }
                }
            }
        };
