// BROKEN — DOES NOT RUN. This reads BEACH_LOCATIONS / FOOD_LOCATIONS /
// ATTRACTION_LOCATIONS / GEMS_LOCATIONS from js/map.js. Those four arrays
// were removed when the map was rewritten to read window.CORFU_LOCATIONS
// directly, so this throws on load, before reaching any write — it is dead
// rather than dangerous. Coordinates now live in js/locations-data.js and
// are edited there directly.

// One-off script for Step 9a: adds lat/lon to every entry in
// js/locations-data.js, sourced from js/map.js's four hardcoded arrays
// (BEACH_LOCATIONS/FOOD_LOCATIONS/ATTRACTION_LOCATIONS/GEMS_LOCATIONS),
// matched by name. Rewrites locations-data.js using the exact same
// banner + JSON.stringify(..., null, 2) format extract-locations.js
// uses, so this is a clean, minimal diff (two new keys per entry).
//
// Run with: node scripts/add-latlon.js
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const mapSrc = fs.readFileSync(path.join(ROOT, 'js', 'map.js'), 'utf8');
function extractArray(varName) {
    const re = new RegExp(varName + '\\s*=\\s*\\[([\\s\\S]*?)\\];');
    const m = mapSrc.match(re);
    if (!m) throw new Error('not found in map.js: ' + varName);
    return eval('[' + m[1] + ']');
}
const MAP_BEACHES = extractArray('BEACH_LOCATIONS');
const MAP_FOOD = extractArray('FOOD_LOCATIONS');
const MAP_ATTR = extractArray('ATTRACTION_LOCATIONS');
const MAP_GEMS = extractArray('GEMS_LOCATIONS');

global.window = {};
require(path.join(ROOT, 'js', 'locations-data.js'));
const L = global.window.CORFU_LOCATIONS;

function cleanName(s) {
    return s
        .replace(/^\d+\.\s*/, '')
        .replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}‍]+$/gu, '')
        .trim();
}
function stripParen(s) {
    return s.replace(/\s*\([^)]*\)\s*$/, '').trim();
}
function buildIndex(mapArr) {
    const idx = new Map();
    mapArr.forEach(loc => {
        idx.set(loc.name.trim(), loc);
        idx.set(stripParen(loc.name.trim()), loc);
    });
    return idx;
}

function insertLatLon(item, lat, lon) {
    // Rebuild the object so lat/lon land right after mapsUrl, keeping every
    // other key and its value/order exactly as it was.
    const out = {};
    for (const key of Object.keys(item)) {
        out[key] = item[key];
        if (key === 'mapsUrl') {
            out.lat = lat;
            out.lon = lon;
        }
    }
    return out;
}

function matchCategory(catName, items, mapArr, getName) {
    const idx = buildIndex(mapArr);
    const unmatched = [];
    const newItems = items.map(item => {
        const raw = getName(item);
        const clean = cleanName(raw);
        const hit = idx.get(raw.trim()) || idx.get(clean) || idx.get(stripParen(clean));
        if (!hit) {
            unmatched.push({ id: item.id, name: raw });
            return item; // leave untouched, no lat/lon
        }
        return insertLatLon(item, hit.lat, hit.lon);
    });
    console.log(`${catName}: ${items.length - unmatched.length}/${items.length} matched`);
    if (unmatched.length) {
        console.log(`  UNMATCHED (left without lat/lon):`);
        unmatched.forEach(u => console.log('   -', u.id, '|', u.name));
    }
    return newItems;
}

const results = {
    beaches: matchCategory('beaches', L.beaches, MAP_BEACHES, i => i.name),
    food: matchCategory('food', L.food, MAP_FOOD, i => i.name),
    attractions: matchCategory('attractions', L.attractions, MAP_ATTR, i => i.title),
    gems: matchCategory('gems', L.gems, MAP_GEMS, i => i.name)
};

const banner =
    '// Auto-generated by scripts/extract-locations.js from the original index.html.\n' +
    '// Do not hand-edit the extracted fields lightly — regenerate via the script\n' +
    '// if the source markup changes. New metadata fields (parking, vibe,\n' +
    '// beachType, bestTime, mapsUrl) were derived by heuristics — see the\n' +
    '// extraction script for exact rules, and spot-check ambiguous cards.\n' +
    '// lat/lon (Step 9a) were added separately by scripts/add-latlon.js,\n' +
    '// matched by name against the arrays in js/map.js.\n';

const out = banner + 'window.CORFU_LOCATIONS = ' + JSON.stringify(results, null, 2) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js', 'locations-data.js'), out, 'utf8');
console.log('Wrote js/locations-data.js');
