// One-off extraction script: parses the CURRENT index.html's #plan-weather
// monthly weather table and produces js/corfu-weather.js
// (window.CORFU_WEATHER = [ { month, dayTemp, seaTemp, rainDays,
// description, highlight }, ... ]).
//
// Run with: node scripts/extract-weather.js
//
// Strategy: mirrors scripts/extract-faq.js / scripts/extract-locations.js —
// parse the DOM with cheerio and serialize the real cell text back out
// verbatim rather than hand-retyping any of the Hebrew content. "highlight"
// captures whether the row carries the "recommended month" styling
// (gt-bg-accent-soft on the <tr>) so the renderer can reproduce the same
// visual distinction without re-deriving it from CSS classes elsewhere.

const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const $ = cheerio.load(html, { decodeEntities: false });

const results = [];

$('#plan-weather table tbody tr').each((i, el) => {
    const $tr = $(el);
    const $tds = $tr.find('> td');
    const highlight = ($tr.attr('class') || '').indexOf('gt-bg-accent-soft') !== -1;

    results.push({
        month: $($tds.get(0)).text().trim(),
        dayTemp: $($tds.get(1)).text().trim(),
        seaTemp: $($tds.get(2)).text().trim(),
        rainDays: $($tds.get(3)).text().trim(),
        description: $($tds.get(4)).text().trim(),
        highlight
    });
});

console.log('extracted weather rows:', results.length);

if (results.length === 0) {
    console.error('\nREFUSING TO WRITE js/corfu-weather.js: extracted 0 rows.');
    console.error('#plan-weather table tbody tr matched nothing — check the selector against');
    console.error('the current index.html markup before re-running.');
    process.exit(1);
}

const banner = `// Auto-generated by scripts/extract-weather.js from the original index.html.
// Do not hand-edit lightly — regenerate via the script if the source markup
// changes. Each entry's fields are plain text (verbatim from the source
// table cells). "highlight" marks the recommended-months styling (May-Sep
// in the original markup, i.e. rows that carried gt-bg-accent-soft on the
// <tr>).
`;

const out = banner + 'window.CORFU_WEATHER = ' + JSON.stringify(results, null, 2) + ';\n';
const targetPath = path.join(ROOT, 'js', 'corfu-weather.js');
fs.writeFileSync(targetPath, out, 'utf8');
console.log('Wrote js/corfu-weather.js (' + results.length + ' rows)');
