// Extracts the About tab's 4 region-character cards from index.html into
// js/corfu-about.js, verbatim (never retyped) - same cheerio-based pattern
// as scripts/extract-locations.js / scripts/extract-faq.js /
// scripts/extract-activities.js. Re-run after any hand-edit to the source
// markup; do not hand-edit js/corfu-about.js directly.
//
// Usage: node scripts/extract-about.js
'use strict';

const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const $ = cheerio.load(html);

const REGION_LABELS = { 'צפון': 'north', 'מזרח': 'east', 'מערב': 'west', 'דרום': 'south' };

const regions = [];
$('#about .grid.grid-cols-1.sm\\:grid-cols-2.xl\\:grid-cols-4 > div').each((i, el) => {
    const $el = $(el);
    const labelHe = $el.find('span').first().text().trim();
    const titleFull = $el.find('h4').first().text().trim();
    const emojiMatch = titleFull.match(/^(\S+)\s*/);
    const emoji = emojiMatch ? emojiMatch[1] : '';
    const title = titleFull.replace(/^\S+\s*/, '').trim();
    const description = $el.find('p').first().text().trim();
    regions.push({
        id: REGION_LABELS[labelHe] || `region-${i + 1}`,
        label: labelHe,
        emoji,
        title,
        description
    });
});

if (regions.length !== 4) {
    throw new Error(`extract-about: expected 4 region cards, found ${regions.length} - aborting, not writing a possibly-truncated file`);
}

const out = `// Auto-generated by scripts/extract-about.js from the original index.html.
// Do not hand-edit lightly — regenerate via the script if the source markup
// changes.
window.CORFU_ABOUT = {
  regions: ${JSON.stringify(regions, null, 2).split('\n').join('\n  ')}
};
`;

fs.writeFileSync(path.join(ROOT, 'js/corfu-about.js'), out, 'utf8');
console.log(`Extracted ${regions.length} region cards -> js/corfu-about.js`);
regions.forEach(r => console.log(`  ${r.id}: ${r.emoji} ${r.title}`));
