// One-off extraction script: parses the CURRENT index.html's #faq-list
// <details> Q&A pairs and produces js/corfu-faq.js
// (window.CORFU_FAQ = [ { id, q, a, cat }, ... ]).
//
// Run with: node scripts/extract-faq.js
//
// Strategy: mirrors scripts/extract-locations.js — parse the DOM with
// cheerio and serialize the real values back out verbatim (question text,
// answer innerHTML, category attribute) rather than hand-retyping any of
// the Hebrew content. The question is <summary><span> text; the category
// is the details element's data-cat attribute; the answer is the raw
// innerHTML of the trailing <div> (kept as HTML, not textContent, since a
// handful of entries have nested tags like <strong>).

const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');

const ROOT = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const $ = cheerio.load(html, { decodeEntities: false });

const results = [];

$('#faq-list > details').each((i, el) => {
    const $d = $(el);
    const cat = $d.attr('data-cat') || '';
    const q = $d.find('> summary > span').first().text().trim();
    const $answer = $d.find('> div').first();
    const a = ($answer.html() || '').trim();

    results.push({
        id: 'faq-' + (i + 1),
        q,
        a,
        cat
    });
});

console.log('extracted FAQ entries:', results.length);

if (results.length === 0) {
    console.error('\nREFUSING TO WRITE js/corfu-faq.js: extracted 0 entries.');
    console.error('#faq-list > details matched nothing — check the selector against the');
    console.error('current index.html markup before re-running.');
    process.exit(1);
}

const banner = `// Auto-generated by scripts/extract-faq.js from the original index.html.
// Do not hand-edit lightly — regenerate via the script if the source markup
// changes. Each entry's "a" field is the answer <div>'s raw innerHTML
// (verbatim from the source, including any nested tags), not escaped text.
`;

const out = banner + 'window.CORFU_FAQ = ' + JSON.stringify(results, null, 2) + ';\n';
const targetPath = path.join(ROOT, 'js', 'corfu-faq.js');
fs.writeFileSync(targetPath, out, 'utf8');
console.log('Wrote js/corfu-faq.js (' + results.length + ' entries)');
