// One-off script for Step 20b (Phase 2): recolors category/tag badge
// chips across js/locations-data.js's HTML-fragment fields onto the
// 5-color Mediterranean system, instead of the ~14 generic Tailwind hue
// families currently scattered through them.
//
// Why this script and not scripts/extract-locations.js: that script
// re-parses index.html's ORIGINAL static card markup to build
// locations-data.js from scratch - but Phase 1 replaced that markup with
// empty containers + dynamic rendering, so extract-locations.js now finds
// 0 items and would blank the file (confirmed - do not run it again as a
// "regenerate" step). This script instead transforms the CURRENT
// locations-data.js (itself the only remaining source of truth) via
// script, so the change is still regenerable/reviewable and not a manual
// hand-edit of generated output.
//
// Scope: only true badge CHIPS - an element carrying BOTH a bg-{hue}-N
// and a text-{hue}-N class together (a colored pill). Standalone
// text-{hue}-N with no matching bg on the same element (e.g. the small
// emoji icon accents in food/attraction info rows, text-blue-500 with no
// background) are NOT badges and are left untouched - recoloring those
// would be a much broader, unrelated change. Gray/slate family classes
// are structural body text, also left untouched.
//
// Run with: node scripts/recolor-badges.js
const fs = require('fs');
const path = require('path');
const cheerio = require('cheerio');
const ROOT = path.join(__dirname, '..');

const HUE_BUCKET = {
    blue: 'ion', cyan: 'ion', teal: 'ion', indigo: 'ion',
    red: 'gold', orange: 'gold', amber: 'gold', yellow: 'gold', purple: 'gold', pink: 'gold', rose: 'gold',
    green: 'olive', lime: 'olive', emerald: 'olive',
    gray: 'sand', slate: 'sand', zinc: 'sand', stone: 'sand', neutral: 'sand'
};
const HUES = Object.keys(HUE_BUCKET).join('|');
// bg-blue-600/90 style opacity-modified backgrounds included (\/\d+)?
const bgRe = new RegExp(`^bg-(${HUES})-\\d+(/\\d+)?$`);
const textRe = new RegExp(`^text-(${HUES})-\\d+$`);

let chipCount = 0;
let solidCount = 0;
const bucketCounts = {};

function recolorHtml(html) {
    if (!html || html.indexOf('<') === -1) return html;
    const $ = cheerio.load(`<div id="__root">${html}</div>`, { decodeEntities: false });
    $('[class]').each((_, el) => {
        const $el = $(el);
        const classes = ($el.attr('class') || '').split(/\s+/).filter(Boolean);
        const bgToken = classes.find(c => bgRe.test(c));
        const textToken = classes.find(c => textRe.test(c));
        const hasWhiteText = classes.includes('text-white');

        if (bgToken && textToken) {
            // Light-tint pill: bg-{hue}-N + text-{hue}-N pair on the same chip.
            const bgHue = bgToken.match(bgRe)[1];
            const textHue = textToken.match(textRe)[1];
            const bucket = HUE_BUCKET[bgHue] || HUE_BUCKET[textHue];
            if (!bucket) return;
            const newClasses = classes
                .filter(c => c !== bgToken && c !== textToken)
                .concat([`badge-${bucket}-bg`, `badge-${bucket}-text`]);
            $el.attr('class', newClasses.join(' '));
            chipCount++;
            bucketCounts[bucket] = (bucketCounts[bucket] || 0) + 1;
        } else if (bgToken && hasWhiteText) {
            // Solid badge: bg-{hue}-N(/opacity) + text-white (rating/price/
            // score chips) - needs a dark/saturated bg so white text still
            // reads, not the light tint the pill variant uses.
            const bgHue = bgToken.match(bgRe)[1];
            const bucket = HUE_BUCKET[bgHue];
            if (!bucket) return;
            const newClasses = classes
                .filter(c => c !== bgToken)
                .concat([`badge-${bucket}-solid`]);
            $el.attr('class', newClasses.join(' '));
            solidCount++;
            bucketCounts[bucket] = (bucketCounts[bucket] || 0) + 1;
        }
        // else: standalone text-{hue} with no matching bg on this element
        // (icon accents, inline "טיפ:" emphasis, etc.) - not a badge chip,
        // left untouched.
    });
    return $('#__root').html();
}

function recolorItem(item) {
    Object.keys(item).forEach(key => {
        if (typeof item[key] === 'string') {
            item[key] = recolorHtml(item[key]);
        }
    });
    return item;
}

global.window = {};
require(path.join(ROOT, 'js', 'locations-data.js'));
const data = global.window.CORFU_LOCATIONS;

['beaches', 'food', 'attractions', 'gems'].forEach(cat => {
    data[cat] = data[cat].map(recolorItem);
});

const banner =
    '// Auto-generated by scripts/extract-locations.js from the original index.html.\n' +
    '// Do not hand-edit the extracted fields lightly — regenerate via the script\n' +
    '// if the source markup changes. New metadata fields (parking, vibe,\n' +
    '// beachType, bestTime, mapsUrl) were derived by heuristics — see the\n' +
    '// extraction script for exact rules, and spot-check ambiguous cards.\n' +
    '// lat/lon (Step 9a) were added separately by scripts/add-latlon.js,\n' +
    '// matched by name against the arrays in js/map.js.\n' +
    '// Badge colors (Phase 2 Step 20b) were consolidated onto the\n' +
    '// Mediterranean palette by scripts/recolor-badges.js — extract-locations.js\n' +
    '// can no longer regenerate this file (see that script for why), so this\n' +
    '// file is now the source of truth for further transforms.\n';

const out = banner + 'window.CORFU_LOCATIONS = ' + JSON.stringify(data, null, 2) + ';\n';
fs.writeFileSync(path.join(ROOT, 'js', 'locations-data.js'), out, 'utf8');

console.log('Recolored', chipCount, 'pill badges +', solidCount, 'solid badges:', bucketCounts);
console.log('Wrote js/locations-data.js');
